[package]
name = "sanguine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
svg = "0.14.0"
circle = "0.1.8"




