[package]
name = "sanguine_lib"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
svg = "0.14.0"
usvg = "0.36.0"
geo = "0.27.0"
voronator = "0.2.1"


